# Generated by Django 4.2.19 on 2025-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Outdoors', 'Outdoors'), ('Music', 'Music'), ('Arts', 'Arts'), ('Business', 'Business'), ('Community', 'Community'), ('Sports', 'Sports'), ('Food', 'Food'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='other', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
    ]
